addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.28")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
addCompilerPlugin("com.olegpy" %% "better-monadic-for" % "0.3.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.25")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.7")
